News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path('', include('simpleapp.urls')),
   path("accounts/", include("allauth.urls")),
   path('acc/', include("django.contrib.auth.urls")),
   path('acc/', include("accounts.urls")),
]

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICE = [
        (NEWS, 'Новости'),
        (ARTICLE, 'Статья')
    ]
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICE, default=NEWS)
    dateCreate = models.DateTimeField(auto_now_add=True)

    postCategory = models.ManyToManyField(Category, through='PostCategory')

    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'


class PostCategory(models.Model):
    postT = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryT = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    commentCreate = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/simpleapp/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse


class New(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
    )

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICE = [
        (NEWS, 'Новости'),
        (ARTICLE, 'Статья')
    ]
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICE, default='NW')

    description = models.TextField()

    news = models.TextField()

    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',
    )

    time_now = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('new_detail', args=[str(self.id)])

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/news/views.py
from django.shortcuts import render

# Create your views here.

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/new.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}


{% block title %}
New
{% endblock title %}


{% block content %}
<h1>{{ new }}</h1>
Дата публикации:
{{ new.time_now|date:'d M Y' }}
<br>
Текст статьи:
{{ new.news|censor }}
{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <h3>{{ news|length }}</h3>

   <hr>

    {% if perms.simpleapp.add_new %}
    <a href="{% url 'new_create' %}">Добавить новость</a>
    {% endif %}

   {% if news %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Категория</td>
               <td>Текст статьи</td>


               {% if perms.simpleapp.change_new or perms.simpleapp.delete_new %}
               <td>Действия</td>
               {% endif %}
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.name }}</td>
               <td>{{ new.time_now|date:'d M Y' }}</td>
               <td>{{ new.category.name }}</td>
               <td>{{ new.news|truncatechars:20 }}</td>

               <td>
                   {% if perms.simpleapp.change_new %}
                   <a href="{% url 'new_update' pk=new.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.simpleapp.delete_new %}
                   <a href="{% url 'new_delete' new.id %}">Удалить</a>
                   {% endif %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/news_search.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <h3>{{ news|length }}</h3>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if news %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Категория</td>
               <td>Текст статьи</td>
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.name }}</td>
               <td>{{ new.time_now|date:'d M Y' }}</td>
               <td>{{ new.category.name }}</td>
               <td>{{ new.news|truncatechars:20 }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

News-Portal-1-main/News-Portal-1-main/News-Portal-1-main/News Portal1/NewsPaper/templates/products.html
{% extends 'flatpages/default.html' %}

{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Все товары</h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>

   <hr>
   {% if products %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Цена</td>
               <td>Количество</td>
           </tr>

           {% for product in products %}
           <tr>
               <td>{{ product.name }}</td>
               <td>{{ product.description|truncatewords:2 }}</td>
               <td>{{ product.category.name }}</td>
               <td>{{ product.price }}</td>
               <td>{{ product.quantity }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Товаров нет!</h2>
   {% endif %}
{% endblock content %}